package com.example.orphanapp.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFF388E3C)
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_primaryContainer = Color(0xFF1B5E20)
val md_theme_dark_onPrimaryContainer = Color(0xFFC8E6C9)
val md_theme_dark_secondary = Color(0xFF0288D1)
val md_theme_dark_onSecondary = Color(0xFFFFFFFF)
val md_theme_dark_secondaryContainer = Color(0xFF01579B)
val md_theme_dark_onSecondaryContainer = Color(0xFFB3E5FC)
val md_theme_dark_tertiary = Color(0xFFFFC107)
val md_theme_dark_onTertiary = Color(0xFF000000)
val md_theme_dark_tertiaryContainer = Color(0xFFFF8F00)
val md_theme_dark_onTertiaryContainer = Color(0xFF212121)
val md_theme_dark_error = Color(0xFFD32F2F)
val md_theme_dark_onError = Color(0xFFFFFFFF)
val md_theme_dark_errorContainer = Color(0xFFB71C1C)
val md_theme_dark_onErrorContainer = Color(0xFFF44336)
val md_theme_dark_background = Color(0xFF121212)
val md_theme_dark_onBackground = Color(0xFFFFFFFF)
val md_theme_dark_surface = Color(0xFF212121)
val md_theme_dark_onSurface = Color(0xFFFFFFFF)
val md_theme_dark_surfaceVariant = Color(0xFF424242)
val md_theme_dark_onSurfaceVariant = Color(0xFFBDBDBD)
val md_theme_dark_outline = Color(0xFF757575)
